name: 'Simu Rewards'
description: 'trys to claim account rewards and login rewards for all characters on an account'
inputs:
  account:  
    description: 'which account to claim the rewards on'
    required: true
  password:  
    description: 'password to the account'
    required: true
  game:
    description: 'game code'
    required: false
    default: 'GS3'
runs:
  using: "composite"
  steps:
    #- uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: claim rewards
        env:
          ACCOUNT: ${{ inputs.account }}
          PASSWORD: ${{ inputs.password }}
          GAME_CODE: ${{ inputs.game }}
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        shell: bash
        command: cd ${{ github.action_path }} && bun install && bun index.ts
